### ISSUE TITLE
Please use "Free Software" rather than "Open Source"

### ISSUE THREAD

**Issue by windowsrefund** [jjasghar/chef-book#27]
The term "open source" is simply not legitimate and actually undermines the work done by the Free Software community.

https://www.gnu.org/philosophy/open-source-misses-the-point.html

If this important language is corrected, I'll be more than happy to contribute to this project. One of the first things I'll do is add a section for Docker which is a much better provisioner than VirtualBox.

**Comment by cheeseplus** [comment]
The only references I see are specifically referring to Open Source Chef Server in contrast to Enterprise Chef Server (a distinction that existed until Chef 12). As such these are part of the product name and changing the text here would only confuse the very users this guide is trying to inform.

**Comment by jjasghar** [comment]
Agreed @cheeseplus, than's @windowsrefund the point, but there are some major updates that need to happen but I don't think this is one of the higher priority.
